[tool.ruff]

line-length = 88                         
exclude = [                             
  ".git",
  ".github",
  ".gitignore",
  "__pycache__",
  "data",
  ".venv",
  "db",
  "bapp/agents_config",
  "app/rag",
]


[tool.ruff.lint]

select = ["A", "B", "C", "E", "F", "I", "N", "Q", "UP"]
ignore = ["E501", "F401"]


per-file-ignores = { "tests/*.py" = ["F401"] }

[tool.ruff.lint.pep8-naming]

classmethod-decorators = [
  "classmethod",
  "pydantic.field_validator",
  "pydantic.model_validator",
]
