name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
    id-token: write
    contents: read

jobs:
  integration:
    name: Continuous Integresion
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      - name: Lint with Ruff
        run: |
          ruff check .
          echo "✅ Ruff linting passed."

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -v
          echo "✅ Pytest unit tests passed."

  